---
apiVersion: v1
kind: Service
metadata:
  name: config-service-expose
  labels:
    app: config-service
spec:
  ports:
  - name: config-service
    protocol: TCP
    port: 31701
    targetPort: 8888
    nodePort: 31701
  selector:
    app: config-service
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  ports:
  - port: 8761
    targetPort: 8761
    name: config-service
  clusterIP: None
  selector:
    app: config-service
---    
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: config-service
spec:
  serviceName: "config-service"
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - resources:
          requests:
            cpu: 100m
            memory: 192Mi 
        name: config-service
        image: config-service:latest
        ports:
        - containerPort: 8888
        env:
        - name: JAVA_OPTS
          value: |
            -Xmx160m
              -Dspring.profiles.active=cloud
  podManagementPolicy: "Parallel"
